kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: default
  labels:
    app: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/jenkins_home"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: default
  labels:
    app: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
